-- Develop SQL to build summary table for analysis.
-- Get our customers
WITH CUSTOMERS AS (SELECT ID AS CUSTOMER_ID,
FIRST_NAME,
LAST_NAME
FROM RAW.JAFFLE_SHOP.CUSTOMERS),

-- Get customer orders
ORDERS AS (SELECT USER_ID AS CUSTOMER_ID,
ORDER_DATE,
STATUS
FROM RAW.JAFFLE_SHOP.ORDERS 
WHERE STATUS = 'completed'),

-- Summarize orders by cutomer
CUSTOMER_ORDERS AS (SELECT CUSTOMER_ID,
MIN(ORDER_DATE) AS FIRST_ORDER,
MAX(ORDER_DATE) AS MOST_RECENT_ORDER,
COUNT(*) AS ORDER_COUNT
FROM ORDERS
GROUP BY 1),

-- Return final model
FINAL AS (SELECT CUSTOMERS.FIRST_NAME,
CUSTOMERS.LAST_NAME,
CUSTOMER_ORDERS.FIRST_ORDER,
CUSTOMER_ORDERS.MOST_RECENT_ORDER,
COALESCE(CUSTOMER_ORDERS.ORDER_COUNT,0) AS ORDER_COUNT
FROM CUSTOMERS 
LEFT JOIN CUSTOMER_ORDERS USING(CUSTOMER_ID) 
)

SELECT * 
FROM FINAL